# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run.
on:
  workflow_dispatch:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches:
      - '**'    
    tags:
      - '**'    
    paths:
      - '**'

jobs:
  docker-build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Login to docker registry
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: docker build ci
        run: |
          docker build . -t blacs30/protonmail-bridge-docker:latest -t blacs30/protonmail-bridge-docker:${{ github.sha }} -t blacs30/protonmail-bridge-docker:$(cat VERSION)

      - name: docker push
        run: |
          docker push -a blacs30/protonmail-bridge-docker