# This is a basic workflow to help you get started with Actions

name: CI

env:
  PM_VERSION: 1.8.12

# Controls when the action will run.
on:
  workflow_dispatch:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches:
      - '**'    
    tags:
      - '**'    
    paths:
      - '**'

jobs:
  docker-build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Login to docker registry
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: docker build ci
        run: |
          docker build . -t blacs30/protonmail-bridge-docker:latest -t blacs30/protonmail-bridge-docker:${{ github.sha }} -t blacs30/protonmail-bridge-docker:${{ env.PM_VERSION }}

      - name: docker push
        run: |
          docker push -a blacs30/protonmail-bridge-docker

          if [ $GITHUB_REF == "refs/heads/develop" ]; then
            echo "::set-output name=matrix::{\"include\":[{\"cluster\":\"tooling-west-1\",\"environment\":\"dev\"}]}"
          fi
          if [ "$GITHUB_REF" == "refs/heads/master" ]; then
            echo "::set-output name=matrix::{\"include\":[{\"cluster\":\"tooling-west-1\",\"environment\":\"prod\"}]}"
          fi
